<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE albumCollection [
<!ELEMENT albumCollection (info,types,albums)>

<!ELEMENT info (author+,topic)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  index CDATA #IMPLIED>
<!ELEMENT topic (#PCDATA)>

<!ELEMENT types (type)+>
<!ELEMENT type (name,countryOfOrigin,time)>
<!ATTLIST type
  id ID #REQUIRED>
  <!ELEMENT name (#PCDATA)>
<!ELEMENT countryOfOrigin (#PCDATA)>
<!ATTLIST countryOfOrigin
  continent (Europe|Asia|North_America|South_America|Africa|Austalia_and_Oceania|Europe_North_America) #REQUIRED>
<!ELEMENT time (#PCDATA)>
<!ATTLIST time
  age CDATA #IMPLIED>

<!ELEMENT albums (album)+>
<!ELEMENT album (author,title,topSong,releaseDate,
                 price,tracks)>
<!ATTLIST album
  id ID #REQUIRED
  typeId IDREF #REQUIRED>
<!ELEMENT topSong (title,lenght,producer,trackNumber)>
<!ELEMENT releaseDate (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price
  currency NMTOKEN #REQUIRED>
<!ELEMENT lenght (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT trackNumber (#PCDATA)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT tracks (heading, song+)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT song (number, trackTitle, trackLenght)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT trackTitle (#PCDATA)>
<!ELEMENT trackLenght (#PCDATA)>
]>

<?xml-stylesheet type="text/css" href="Albumy.css"?>
<albumCollection>
    <info>
        <author index='210329'>Marek Szafran</author>
        <topic>Music genres and albums:</topic>
    </info>
    <types>
        <type id="G1">
            <name>Hip-Hop</name>
            <countryOfOrigin continent="North_America">USA</countryOfOrigin>
            <time age="XX">70's</time>
        </type>

        <type id="G2">
            <name>Pop</name>
            <countryOfOrigin continent="Europe_North_America">USA/UK</countryOfOrigin>
            <time age="XX"> 60's</time>
        </type>

        <type id="G3">
            <name>Rock</name>
            <countryOfOrigin continent="North_America">USA</countryOfOrigin>
            <time age="XX">40's</time>
        </type>

        <type id="G4">
            <name>Clasical Music</name>
            <countryOfOrigin continent="Europe">European countries</countryOfOrigin>
            <time age="XI">50's</time>
        </type>

        <type id="G5">
            <name>Metal</name>
            <countryOfOrigin continent="Europe_North_America">USA/UK</countryOfOrigin>
            <time age="XX">60's</time>
        </type>

        <type id="G6">
            <name>Disco polo</name>
            <countryOfOrigin continent="Europe">Poland</countryOfOrigin>
            <time age="XX">80's</time>
        </type>
    </types>

    <albums>
        <album id="A1" typeId='G1'>
            <author>Paluch</author>
            <title>Czerwony Dywan</title>
            <topSong>
                <title>"Ładni Smutni Ludzie"</title>
                <lenght>3:36</lenght>
                <producer>SoDrumatic</producer>
                <trackNumber>4</trackNumber>
            </topSong>
            <releaseDate>2018-12-07</releaseDate>
            <price currency="zł">34,99</price>
            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>Intro</trackTitle>
                    <trackLenght>2:55</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>Czerwony Dywan</trackTitle>
                    <trackLenght>3:45</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>Balans</trackTitle>
                    <trackLenght>4:30</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Ładzni smutni ludzie</trackTitle>
                    <trackLenght>3:36</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>Nie myśl o tym</trackTitle>
                    <trackLenght>4:02</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>Nowa Polska</trackTitle>
                    <trackLenght>3:40</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>Mój kościół</trackTitle>
                    <trackLenght>4:11</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>Sidła</trackTitle>
                    <trackLenght>3:18</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Opozycja</trackTitle>
                    <trackLenght>3:43</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>Spłata</trackTitle>
                    <trackLenght>4:05</trackLenght>
                </song>
                <song>
                    <number>11</number>
                    <trackTitle>Pudle</trackTitle>
                    <trackLenght>3:26</trackLenght>
                </song>
                <song>
                    <number>12</number>
                    <trackTitle>Amalgamat</trackTitle>
                    <trackLenght>4:05</trackLenght>
                </song>
                <song>
                    <number>13</number>
                    <trackTitle>Peeling</trackTitle>
                    <trackLenght>4:23</trackLenght>
                </song>
                <song>
                    <number>14</number>
                    <trackTitle>Życie wieczne</trackTitle>
                    <trackLenght>3:07</trackLenght>
                </song>
            </tracks>
        </album>

        <album id="A2" typeId='G1'>
            <author>Sokól</author>
            <title>Wojtek Sokół</title>
            <topSong>
                <title>"Lepiej jak jest lepiej"</title>
                <lenght>4:17</lenght>
                <producer>Sokół</producer>
                <trackNumber>2</trackNumber>
            </topSong>
            <releaseDate>2019-02-15</releaseDate>
            <price currency="zł">38,99</price>
            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>Hybryda</trackTitle>
                    <trackLenght>3:59</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>Lepiej jak jest lepiej</trackTitle>
                    <trackLenght>4:17</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>Pluszowy</trackTitle>
                    <trackLenght>3:30</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Pomyłka</trackTitle>
                    <trackLenght>3:32</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>Sprytny eskimos</trackTitle>
                    <trackLenght>4:14</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>I tak i nie</trackTitle>
                    <trackLenght>3:33</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>Za ręce</trackTitle>
                    <trackLenght>4:47</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>Nie da na da</trackTitle>
                    <trackLenght>3:41</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Napad na bankiet</trackTitle>
                    <trackLenght>4:48</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>Z tobą</trackTitle>
                    <trackLenght>4:14</trackLenght>
                </song>
                <song>
                    <number>11</number>
                    <trackTitle>Skażony</trackTitle>
                    <trackLenght>3:43</trackLenght>
                </song>
                <song>
                    <number>12</number>
                    <trackTitle>MC Hasselblad</trackTitle>
                    <trackLenght>3:55</trackLenght>
                </song>
                <song>
                    <number>13</number>
                    <trackTitle>Koniec gatunku</trackTitle>
                    <trackLenght>5:00</trackLenght>
                </song>
                <song>
                    <number>14</number>
                    <trackTitle>Chcemy być wyżej</trackTitle>
                    <trackLenght>3:09</trackLenght>
                </song>
            </tracks>
        </album>

        <album id="A3" typeId='G2'>
            <author>LP</author>
            <title>Heart to Mouth</title>
            <topSong>
                <title>"Girls Go Wild"</title>
                <lenght>3:44</lenght>
                <producer>Del Rio</producer>
                <trackNumber>4</trackNumber>
            </topSong>
            <releaseDate>2018-12-07</releaseDate>
            <price currency="zł">38,99</price>

            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>Dreamcatcher</trackTitle>
                    <trackLenght>3:15</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>When I'm over You</trackTitle>
                    <trackLenght>4:27</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>One night in the sun</trackTitle>
                    <trackLenght>4:24</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Girls go wild</trackTitle>
                    <trackLenght>3:44</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>Recovery</trackTitle>
                    <trackLenght>3:52</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>The Power</trackTitle>
                    <trackLenght>4:38</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>Dreamer</trackTitle>
                    <trackLenght>3:25</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>House on fire</trackTitle>
                    <trackLenght>3:01</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Hey nice to know ya</trackTitle>
                    <trackLenght>3:24</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>Die for your love</trackTitle>
                    <trackLenght>3:40</trackLenght>
                </song>
                <song>
                    <number>11</number>
                    <trackTitle>Shaken</trackTitle>
                    <trackLenght>3:45</trackLenght>
                </song>
                <song>
                    <number>12</number>
                    <trackTitle>Special</trackTitle>
                    <trackLenght>4:21</trackLenght>
                </song>
            </tracks>
        </album>

        <album id="A4" typeId='G2'>
            <author>Dawid Podsiadło</author>
            <title>Malomiasteczkowy</title>
            <topSong>
                <title>"Małomiasteczkowy"</title>
                <lenght>3:23</lenght>
                <producer>Bartosz Dziedzic</producer>
                <trackNumber>3</trackNumber>
            </topSong>
            <releaseDate>2018-06-06</releaseDate>
            <price currency="zł">36,99</price>

            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>Cantate tutti</trackTitle>
                    <trackLenght>3:07</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>Dżins</trackTitle>
                    <trackLenght>5:12</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>Małomiesteczkowy</trackTitle>
                    <trackLenght>3:23</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Najnowszy klip</trackTitle>
                    <trackLenght>3:50</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>Trofea</trackTitle>
                    <trackLenght>3:45</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>Nie ma fal</trackTitle>
                    <trackLenght>3:58</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>LIS</trackTitle>
                    <trackLenght>4:30</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>Co mówimy?</trackTitle>
                    <trackLenght>3:38</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Nie kłami</trackTitle>
                    <trackLenght>3:16</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>Matylda</trackTitle>
                    <trackLenght>5:14</trackLenght>
                </song>
            </tracks>
        </album>

        <album id="A5" typeId='G3'>
            <author>Nirvana</author>
            <title>Nevermind</title>
            <topSong>
                <title>"Smells Like Teen Spirit"</title>
                <lenght>5:02</lenght>
                <producer>Butch Vig</producer>
                <trackNumber>1</trackNumber>
            </topSong>
            <releaseDate>1991-09-24</releaseDate>
            <price currency="zł">34,99</price>
            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>Smells like ten spirits</trackTitle>
                    <trackLenght>5:02</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>In bloom-Neverwind Version</trackTitle>
                    <trackLenght>4:15</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>Come As You Are</trackTitle>
                    <trackLenght>3:39</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Breed</trackTitle>
                    <trackLenght>3:04</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>Lithium</trackTitle>
                    <trackLenght>4:17</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>Polly</trackTitle>
                    <trackLenght>2:54</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>Territorials Pissings</trackTitle>
                    <trackLenght>2:23</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>Drain you</trackTitle>
                    <trackLenght>3:44</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Lounge act</trackTitle>
                    <trackLenght>2:36</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>Stay away</trackTitle>
                    <trackLenght>3:31</trackLenght>
                </song>
                <song>
                    <number>11</number>
                    <trackTitle>On a plain</trackTitle>
                    <trackLenght>3:14</trackLenght>
                </song>
                <song>
                    <number>12</number>
                    <trackTitle>Something in the way</trackTitle>
                    <trackLenght>3:52</trackLenght>
                </song>
                <song>
                    <number>13</number>
                    <trackTitle>Endless, nameless</trackTitle>
                    <trackLenght>6:43</trackLenght>
                </song>
            </tracks>
        </album>

        <album id="A6" typeId='G3'>
            <author>Guns N' Roses</author>
            <title>Appetite For Destruction</title>
            <topSong>
                <title>"Sweet Child O' Mine"</title>
                <lenght>5:55</lenght>
                <producer>Mike Clink</producer>
                <trackNumber>9</trackNumber>
            </topSong>
            <releaseDate>1987-07-21</releaseDate>
            <price currency="zł">18,99</price>
            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>Welcome to the jungle</trackTitle>
                    <trackLenght>4:33</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>It's so easy</trackTitle>
                    <trackLenght>3:23</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>Nightrain</trackTitle>
                    <trackLenght>4:28</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Out ta get me</trackTitle>
                    <trackLenght>4:24</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>Mr. Brownstone</trackTitle>
                    <trackLenght>3:49</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>Paradise City</trackTitle>
                    <trackLenght>6:46</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>My Michelle</trackTitle>
                    <trackLenght>3:40</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>Think about you</trackTitle>
                    <trackLenght>3:52</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Sweet Child O' mine</trackTitle>
                    <trackLenght>5:56</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>You're crazy</trackTitle>
                    <trackLenght>3:26</trackLenght>
                </song>
                <song>
                    <number>11</number>
                    <trackTitle>Anything goes</trackTitle>
                    <trackLenght>3:26</trackLenght>
                </song>
                <song>
                    <number>12</number>
                    <trackTitle>Rochet Queen</trackTitle>
                    <trackLenght>4:05</trackLenght>
                </song>
            </tracks>
        </album>

        <album id="A7" typeId='G4'>
            <author>Yann Tiersen</author>
            <title>Amelie from Montmartre (Original SoundTrack</title>
            <topSong>
                <title>"Comptine d'un autre été : L'après-midi"</title>
                <lenght>2:20</lenght>
                <producer>Yann Tiersen</producer>
                <trackNumber>4</trackNumber>
            </topSong>
            <releaseDate>2001-04-23</releaseDate>
            <price currency="zł">31,99</price>
            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>I've never been there</trackTitle>
                    <trackLenght>1:34</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>Les jours tristes</trackTitle>
                    <trackLenght>3:03</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>La Valse d'Amelie</trackTitle>
                    <trackLenght>2:16</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Compione d'un autre ete</trackTitle>
                    <trackLenght>2:21</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>The drowned girl</trackTitle>
                    <trackLenght>2:03</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>L'Autre valse d'Amelie</trackTitle>
                    <trackLenght>1:33</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>Guilty</trackTitle>
                    <trackLenght>3:13</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>A quai</trackTitle>
                    <trackLenght>3:32</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Le Moulin</trackTitle>
                    <trackLenght>4:28</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>Not that simple</trackTitle>
                    <trackLenght>1:53</trackLenght>
                </song>
                <song>
                    <number>11</number>
                    <trackTitle>La Valse d'Amelie</trackTitle>
                    <trackLenght>2:00</trackLenght>
                </song>
                <song>
                    <number>12</number>
                    <trackTitle>La Valse des vieux os</trackTitle>
                    <trackLenght>2:20</trackLenght>
                </song>
                <song>
                    <number>13</number>
                    <trackTitle>Dispute</trackTitle>
                    <trackLenght>4:15</trackLenght>
                </song>
                <song>
                    <number>14</number>
                    <trackTitle>Si tu n'stis pas la</trackTitle>
                    <trackLenght>3:29</trackLenght>
                </song>
                <song>
                    <number>15</number>
                    <trackTitle>Evening party</trackTitle>
                    <trackLenght>2:56</trackLenght>
                </song>
                <song>
                    <number>16</number>
                    <trackTitle>La Decouverte</trackTitle>
                    <trackLenght>3:29</trackLenght>
                </song>
                <song>
                    <number>17</number>
                    <trackTitle>On the wire</trackTitle>
                    <trackLenght>4:24</trackLenght>
                </song>
                <song>
                    <number>18</number>
                    <trackTitle>Banquet</trackTitle>
                    <trackLenght>1:31</trackLenght>
                </song>
                <song>
                    <number>19</number>
                    <trackTitle>La valse d'Amelie</trackTitle>
                    <trackLenght>2:39</trackLenght>
                </song>
                <song>
                    <number>20</number>
                    <trackTitle>The waltz of the monster</trackTitle>
                    <trackLenght>3:40</trackLenght>
                </song>
                <song>
                    <number>21</number>
                    <trackTitle>L'Autre valse d'Amelie</trackTitle>
                    <trackLenght>1:41</trackLenght>
                </song>
                <song>
                    <number>22</number>
                    <trackTitle>Les deux pianos</trackTitle>
                    <trackLenght>1:58</trackLenght>
                </song>
                <song>
                    <number>23</number>
                    <trackTitle>Comptine d'un autre ete</trackTitle>
                    <trackLenght>2:01</trackLenght>
                </song>
                <song>
                    <number>24</number>
                    <trackTitle>La Maison</trackTitle>
                    <trackLenght>2:04</trackLenght>
                </song>
                <song>
                    <number>25</number>
                    <trackTitle>La valse d'Amelie</trackTitle>
                    <trackLenght>2:03</trackLenght>
                </song>
            </tracks>
        </album>

        <album id="A8" typeId='G4'>
            <author>Hans Zimmer</author>
            <title>Interstellar (Original Motion Picture Sountrack)</title>
            <topSong>
                <title>"Cornfield Chase"</title>
                <lenght>2:07</lenght>
                <producer>Hans Zimmer</producer>
                <trackNumber>2</trackNumber>
            </topSong>
            <releaseDate>2014-11-17</releaseDate>
            <price currency="zł">43,99</price>
            <tracks>
                <heading>Track List:</heading>
                <song>
                    <number>1</number>
                    <trackTitle>Dreaming of the crash</trackTitle>
                    <trackLenght>3:56</trackLenght>
                </song>
                <song>
                    <number>2</number>
                    <trackTitle>Corbfield chase</trackTitle>
                    <trackLenght>2:07</trackLenght>
                </song>
                <song>
                    <number>3</number>
                    <trackTitle>Dust</trackTitle>
                    <trackLenght>5:41</trackLenght>
                </song>
                <song>
                    <number>4</number>
                    <trackTitle>Day one</trackTitle>
                    <trackLenght>3:19</trackLenght>
                </song>
                <song>
                    <number>5</number>
                    <trackTitle>Stay</trackTitle>
                    <trackLenght>6:52</trackLenght>
                </song>
                <song>
                    <number>6</number>
                    <trackTitle>Messege form home</trackTitle>
                    <trackLenght>1:41</trackLenght>
                </song>
                <song>
                    <number>7</number>
                    <trackTitle>The wormhole</trackTitle>
                    <trackLenght>1:31</trackLenght>
                </song>
                <song>
                    <number>8</number>
                    <trackTitle>Mountains</trackTitle>
                    <trackLenght>3:39</trackLenght>
                </song>
                <song>
                    <number>9</number>
                    <trackTitle>Afraid of time</trackTitle>
                    <trackLenght>2:33</trackLenght>
                </song>
                <song>
                    <number>10</number>
                    <trackTitle>A place among stars</trackTitle>
                    <trackLenght>3:27</trackLenght>
                </song>
                <song>
                    <number>11</number>
                    <trackTitle>Running out</trackTitle>
                    <trackLenght>1:57</trackLenght>
                </song>
                <song>
                    <number>12</number>
                    <trackTitle>I'm going home</trackTitle>
                    <trackLenght>5:49</trackLenght>
                </song>
                <song>
                    <number>13</number>
                    <trackTitle>Coward</trackTitle>
                    <trackLenght>8:27</trackLenght>
                </song>
                <song>
                    <number>14</number>
                    <trackTitle>Detach</trackTitle>
                    <trackLenght>6:42</trackLenght>
                </song>
                <song>
                    <number>15</number>
                    <trackTitle>S.T.A.Y.</trackTitle>
                    <trackLenght>6:24</trackLenght>
                </song>
                <song>
                    <number>16</number>
                    <trackTitle>Where we're going</trackTitle>
                    <trackLenght>7:41</trackLenght>
                </song>
                <song>